# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MyWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'


  # Pods for MyWeatherApp

  target 'MyWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'
  end

  target 'MyWeatherAppUITests' do
    # Pods for testing
pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'
  end

end



